DROP TABLE HomeWorks
DROP TABLE Lessons
DROP TABLE ScheduleDays
DROP TABLE ScheduleWeeks
DROP TABLE SnUsers
DROP TABLE Groups
DROP TABLE Courses
DROP TABLE Facilities
DROP TABLE Universities
DROP TABLE ErrorLogs
DROP TABLE ActivityLogs
DROP TABLE Teachers